//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Card
{
    public int Id { get; set; }
    public string PAN { get; set; }
    public int ExpirationMonth { get; set; }
    public int ExpirationYear { get; set; }
    public string SecurityCode { get; set; }
    public string CardName { get; set; }
    public int IdClient { get; set; }
    public int Quota { get; set; }
    public string Brand { get; set; }
    public bool Active { get; set; }

    public virtual Client Client { get; set; }
}

public partial class Client
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Client()
    {
        this.Card = new HashSet<Card>();
    }

    public int Id { get; set; }
    public string Name { get; set; }
    public bool Active { get; set; }
    public string Password { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Card> Card { get; set; }
}
